language: elixir

elixir:
  - '1.6.4'

otp_release:
  - '20.0.0'

addons:
  postgresql: '9.4'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test