language: elixir

elixir:
  - 1.6

otp_release:
  - 20.1

addons:
  postgresql: '9.4'

services:
  - postgresql

before_script:
  - cp config/ci.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test